version: '3'

silent: true

tasks:

  clean:
    desc: Clean built artefacts
    cmds:
      - cmd: rm -rf .vitepress/cache
      - cmd: rm -rf .vitepress/dist

  serve:
    desc: Start the documentation server locally
    cmds:
      - cmd: npm run docs:dev

  build:
    desc: Build the documentation
    cmds:
      - cmd: npm run docs:build

  preview:
    desc: Preview built documentation
    cmds:
      - cmd: npm run docs:build
      - cmd: npm run docs:preview
